# Generated by Django 2.2.2 on 2019-06-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_number', models.IntegerField()),
                ('rooms_summary', models.TextField()),
                ('number_of_room', models.IntegerField()),
                ('rooms_pic', models.ImageField(blank=True, null=True, upload_to='room_image')),
            ],
        ),
    ]
